import type { Classification, Shape, Source } from "./types";

export type SeedContact = {
  lat: number;
  lng: number;
  locationLabel: string;
  region: string;
  occurredAt: string;
  shape: Shape;
  durationSec: number | null;
  summary: string;
  classification: Classification;
  confidence: number;
  source: Source;
};

export const SEED_CONTACTS: SeedContact[] = [
  {
    lat: 31.57,
    lng: -117.89,
    locationLabel: "Off San Diego, Pacific",
    region: "North America",
    occurredAt: "2004-11-14T14:20:00Z",
    shape: "tic-tac",
    durationSec: 240,
    summary:
      "Carrier strike-group sensors tracked a white, featureless craft that dropped from ~80,000 ft, hovered, then accelerated beyond visual. Multiple aircrew and radar tracks.",
    classification: "anomalous",
    confidence: 92,
    source: "archive",
  },
  {
    lat: 33.45,
    lng: -112.07,
    locationLabel: "Phoenix, Arizona",
    region: "North America",
    occurredAt: "1997-03-13T02:30:00Z",
    shape: "lights",
    durationSec: 1800,
    summary:
      "A V-shaped formation of lights moved slowly over the valley. Thousands of witnesses. Official explanation cites flares; geometry of the formation remains disputed.",
    classification: "unidentified",
    confidence: 74,
    source: "archive",
  },
  {
    lat: 52.09,
    lng: 1.45,
    locationLabel: "Rendlesham Forest, UK",
    region: "Europe",
    occurredAt: "1980-12-26T03:00:00Z",
    shape: "unknown",
    durationSec: 3600,
    summary:
      "USAF security personnel reported a glowing object among the trees near RAF Woodbridge, with later radiation readings at the landing site.",
    classification: "unidentified",
    confidence: 68,
    source: "archive",
  },
  {
    lat: 50.85,
    lng: 4.35,
    locationLabel: "Brabant, Belgium",
    region: "Europe",
    occurredAt: "1989-11-29T17:20:00Z",
    shape: "triangle",
    durationSec: 5400,
    summary:
      "Nationwide wave of large, silent triangular craft. F-16 intercepts recorded lock-ons that broke with extreme acceleration.",
    classification: "anomalous",
    confidence: 81,
    source: "archive",
  },
  {
    lat: -37.93,
    lng: 145.16,
    locationLabel: "Westall, Melbourne",
    region: "Oceania",
    occurredAt: "1966-04-06T10:00:00Z",
    shape: "disc",
    durationSec: 1200,
    summary:
      "More than 200 students and staff watched a silver disc descend into a paddock, then depart at speed. Ground traces reported in grass.",
    classification: "unidentified",
    confidence: 71,
    source: "archive",
  },
  {
    lat: 35.69,
    lng: 51.39,
    locationLabel: "Tehran FIR",
    region: "Middle East",
    occurredAt: "1976-09-19T00:30:00Z",
    shape: "disc",
    durationSec: 2400,
    summary:
      "Imperial Iranian Air Force intercept. Avionics and ground communications failed as the jet closed; a secondary object detached and approached.",
    classification: "anomalous",
    confidence: 86,
    source: "archive",
  },
  {
    lat: 66.0,
    lng: -147.0,
    locationLabel: "Interior Alaska FIR",
    region: "North America",
    occurredAt: "1986-11-17T17:11:00Z",
    shape: "unknown",
    durationSec: 3000,
    summary:
      "JAL 1628 crew described a huge dark body with lights pacing the 747. Civilian and military radar returned intermittent corroboration.",
    classification: "unidentified",
    confidence: 77,
    source: "archive",
  },
  {
    lat: 41.978,
    lng: -87.907,
    locationLabel: "Chicago O'Hare",
    region: "North America",
    occurredAt: "2006-11-07T16:15:00Z",
    shape: "disc",
    durationSec: 300,
    summary:
      "Ramp and tower personnel reported a grey disc over Gate C17 that punched a hole in the overcast as it departed. No radar track logged.",
    classification: "unidentified",
    confidence: 64,
    source: "archive",
  },
  {
    lat: 32.22,
    lng: -98.2,
    locationLabel: "Stephenville, Texas",
    region: "North America",
    occurredAt: "2008-01-08T18:15:00Z",
    shape: "lights",
    durationSec: 600,
    summary:
      "Multiple witnesses, including a constable and a pilot, described a mile-wide formation of lights. FAA later released radar plots of unknown returns.",
    classification: "unidentified",
    confidence: 73,
    source: "archive",
  },
  {
    lat: 18.49,
    lng: -67.13,
    locationLabel: "Aguadilla, Puerto Rico",
    region: "Caribbean",
    occurredAt: "2015-04-25T21:20:00Z",
    shape: "orb",
    durationSec: 180,
    summary:
      "DHS infrared video of an object that crossed the shoreline, entered water, and appeared to split without slowing.",
    classification: "anomalous",
    confidence: 84,
    source: "archive",
  },
  {
    lat: -0.73,
    lng: -48.28,
    locationLabel: "Colares, Brazil",
    region: "South America",
    occurredAt: "1977-10-17T02:00:00Z",
    shape: "lights",
    durationSec: null,
    summary:
      "Operation Saucer recorded beams of light striking residents; military teams documented burns and local panic across the island.",
    classification: "unidentified",
    confidence: 70,
    source: "archive",
  },
  {
    lat: -21.55,
    lng: -45.43,
    locationLabel: "Varginha, Brazil",
    region: "South America",
    occurredAt: "1996-01-20T08:30:00Z",
    shape: "unknown",
    durationSec: null,
    summary:
      "City-wide reports of a crippled craft and subsequent military activity. Hard sensor data is thin; the social record is dense.",
    classification: "unidentified",
    confidence: 48,
    source: "archive",
  },
  {
    lat: -17.78,
    lng: 31.05,
    locationLabel: "Ruwa, Zimbabwe",
    region: "Africa",
    occurredAt: "1994-09-16T10:15:00Z",
    shape: "disc",
    durationSec: 900,
    summary:
      "Sixty schoolchildren described a landed craft and figures at Ariel School. Interviews were consistent on core details, disputed on interpretation.",
    classification: "unidentified",
    confidence: 55,
    source: "archive",
  },
  {
    lat: -20.51,
    lng: -29.32,
    locationLabel: "Trindade Island",
    region: "South Atlantic",
    occurredAt: "1958-01-16T12:00:00Z",
    shape: "disc",
    durationSec: 180,
    summary:
      "Brazilian Navy survey ship Almirante Saldanha. Photographs of a Saturn-shaped object taken in daylight by a civilian photographer aboard.",
    classification: "unidentified",
    confidence: 66,
    source: "archive",
  },
  {
    lat: -42.4,
    lng: 173.68,
    locationLabel: "Kaikoura, New Zealand",
    region: "Oceania",
    occurredAt: "1978-12-31T00:10:00Z",
    shape: "orb",
    durationSec: 2400,
    summary:
      "Argosy cargo flights recorded luminous objects on airborne radar and on 16mm film, with Wellington ATC corroboration.",
    classification: "anomalous",
    confidence: 79,
    source: "archive",
  },
  {
    lat: 62.82,
    lng: 11.18,
    locationLabel: "Hessdalen, Norway",
    region: "Europe",
    occurredAt: "2023-11-04T21:40:00Z",
    shape: "orb",
    durationSec: 420,
    summary:
      "Valley known for recurring luminous phenomena. Optical station logged a slow-moving plasma-like return with no corresponding ADS-B.",
    classification: "unidentified",
    confidence: 61,
    source: "sensor",
  },
  {
    lat: 51.66,
    lng: 39.2,
    locationLabel: "Voronezh, Russia",
    region: "Europe",
    occurredAt: "1989-09-27T18:00:00Z",
    shape: "disc",
    durationSec: 1800,
    summary:
      "Park witnesses, including children, described a landed spherical craft. TASS reported it; independent physical evidence is limited.",
    classification: "likely-prosaic",
    confidence: 38,
    source: "archive",
  },
  {
    lat: 39.91,
    lng: 116.39,
    locationLabel: "Beijing FIR",
    region: "East Asia",
    occurredAt: "2010-07-07T20:40:00Z",
    shape: "lights",
    durationSec: 900,
    summary:
      "Capital Airport delayed arrivals after a luminous object was reported in the approach corridor. Later attributed by some to a missile test; timing is imperfect.",
    classification: "likely-prosaic",
    confidence: 52,
    source: "archive",
  },
  {
    lat: 34.06,
    lng: -106.89,
    locationLabel: "Socorro, New Mexico",
    region: "North America",
    occurredAt: "1964-04-24T17:45:00Z",
    shape: "disc",
    durationSec: 300,
    summary:
      "Officer Lonnie Zamora reported an egg-shaped object and two figures. Landing traces and burned brush were documented the same evening.",
    classification: "unidentified",
    confidence: 72,
    source: "archive",
  },
  {
    lat: -24.5,
    lng: -69.25,
    locationLabel: "Atacama high plateau, Chile",
    region: "South America",
    occurredAt: "2022-08-11T01:12:00Z",
    shape: "orb",
    durationSec: 760,
    summary:
      "ALMA auxiliary camera caught a steady, non-stellar source tracking against the sky with no satellite TLE match in a 20-minute window.",
    classification: "sensor-contact",
    confidence: 69,
    source: "sensor",
  },
  {
    lat: -77.84,
    lng: 166.67,
    locationLabel: "McMurdo Sound, Antarctica",
    region: "Antarctica",
    occurredAt: "2023-06-02T11:05:00Z",
    shape: "cylinder",
    durationSec: 210,
    summary:
      "Station weather radar painted a cylindrical return at low altitude in polar night. Visual confirmation impossible; balloon inventory was complete.",
    classification: "sensor-contact",
    confidence: 58,
    source: "sensor",
  },
  {
    lat: 12.05,
    lng: -160.2,
    locationLabel: "Central Pacific corridor",
    region: "Pacific",
    occurredAt: "2026-04-18T06:44:00Z",
    shape: "tic-tac",
    durationSec: 95,
    summary:
      "Maritime patrol FLIR acquired a pale, wingless body transiting 0.4 Mach with no exhaust plume. Track dropped after a near-instant heading change.",
    classification: "sensor-contact",
    confidence: 80,
    source: "sensor",
  },
  {
    lat: 56.1,
    lng: 18.4,
    locationLabel: "Baltic Sea",
    region: "Europe",
    occurredAt: "2024-10-09T22:18:00Z",
    shape: "lights",
    durationSec: 540,
    summary:
      "Two NATO maritime patrols reported a formation of four white lights holding station over international waters, then extinguishing in sequence.",
    classification: "unidentified",
    confidence: 63,
    source: "sensor",
  },
  {
    lat: 1.26,
    lng: 103.85,
    locationLabel: "Singapore Strait",
    region: "Southeast Asia",
    occurredAt: "2026-01-22T19:03:00Z",
    shape: "orb",
    durationSec: 130,
    summary:
      "Vessel AIS cameras recorded a bright sphere pacing a tanker at 80 m altitude, then climbing vertically out of frame. No NOTAM for UAV tests.",
    classification: "sensor-contact",
    confidence: 67,
    source: "sensor",
  },
  {
    lat: 13.44,
    lng: 144.79,
    locationLabel: "Guam sensor net",
    region: "Pacific",
    occurredAt: "2026-07-03T14:51:00Z",
    shape: "triangle",
    durationSec: 70,
    summary:
      "Multi-static radar briefed a low-observable triangular return that crossed the island west-to-east below commercial flight levels, no transponder.",
    classification: "sensor-contact",
    confidence: 76,
    source: "sensor",
  },
  {
    lat: -33.92,
    lng: 18.42,
    locationLabel: "Cape Town FIR",
    region: "Africa",
    occurredAt: "2025-09-14T20:26:00Z",
    shape: "disc",
    durationSec: 320,
    summary:
      "Approach control and two airliners reported a metallic disc holding over Table Bay. Track faded as the object climbed through FL180.",
    classification: "unidentified",
    confidence: 71,
    source: "sensor",
  },
  {
    lat: 19.07,
    lng: 72.88,
    locationLabel: "Mumbai coastal",
    region: "South Asia",
    occurredAt: "2024-05-02T21:10:00Z",
    shape: "orb",
    durationSec: 480,
    summary:
      "A slow amber orb drifted along the Marine Drive skyline. Photometry suggests a single source, not a drone swarm. Likely lantern cluster remains possible.",
    classification: "likely-prosaic",
    confidence: 44,
    source: "field-report",
  },
  {
    lat: -1.29,
    lng: 36.82,
    locationLabel: "Nairobi highlands",
    region: "Africa",
    occurredAt: "2025-02-19T03:41:00Z",
    shape: "lights",
    durationSec: 900,
    summary:
      "Game-park rangers logged a silent string of lights that reversed heading without turning radius. No helicopter activity on the night sheet.",
    classification: "unidentified",
    confidence: 57,
    source: "field-report",
  },
  {
    lat: 64.13,
    lng: -21.82,
    locationLabel: "Reykjavik corridor",
    region: "North Atlantic",
    occurredAt: "2024-12-11T00:08:00Z",
    shape: "cylinder",
    durationSec: 160,
    summary:
      "Oceanic radar painted a cylindrical return at FL320 with zero groundspeed for 90 seconds, then a 1,200 kt sprint west. Correlation with space debris failed.",
    classification: "anomalous",
    confidence: 82,
    source: "sensor",
  },
  {
    lat: 60.0,
    lng: -85.0,
    locationLabel: "Hudson Bay",
    region: "North America",
    occurredAt: "2025-11-08T05:22:00Z",
    shape: "unknown",
    durationSec: 240,
    summary:
      "Canadian NORAD feed flagged an unidentified low-altitude contact over ice. Intermittent IFF. Visual intercept was weathered out.",
    classification: "sensor-contact",
    confidence: 60,
    source: "sensor",
  },
  {
    lat: 53.5,
    lng: 108.0,
    locationLabel: "Lake Baikal",
    region: "North Asia",
    occurredAt: "2023-03-21T16:00:00Z",
    shape: "disc",
    durationSec: 600,
    summary:
      "Ice fishermen and a hydrology team described a disc that appeared to enter the lake without splash. Sonar later recorded an unexplained layer disturbance.",
    classification: "unidentified",
    confidence: 49,
    source: "field-report",
  },
  {
    lat: 76.0,
    lng: -41.0,
    locationLabel: "Greenland ice cap",
    region: "Arctic",
    occurredAt: "2024-08-30T09:17:00Z",
    shape: "tic-tac",
    durationSec: 45,
    summary:
      "Ice-penetrating radar campaign recorded a fast, compact return 400 m above the ice with no corresponding aircraft plan.",
    classification: "sensor-contact",
    confidence: 65,
    source: "sensor",
  },
  {
    lat: -40.0,
    lng: 158.0,
    locationLabel: "Tasman Sea",
    region: "Oceania",
    occurredAt: "2026-02-27T11:33:00Z",
    shape: "lights",
    durationSec: 210,
    summary:
      "P-8 crew on a training track filmed two white lights pacing at 200 ft. Lights merged, then the contact was gone on radar within one sweep.",
    classification: "anomalous",
    confidence: 78,
    source: "sensor",
  },
  {
    lat: -7.3,
    lng: 72.4,
    locationLabel: "Chagos corridor",
    region: "Indian Ocean",
    occurredAt: "2025-06-16T02:05:00Z",
    shape: "unknown",
    durationSec: 110,
    summary:
      "Over-the-horizon radar briefed a high-Mach contact that decelerated to hover, then departed on a reciprocal. No allied exercise on the board.",
    classification: "sensor-contact",
    confidence: 74,
    source: "sensor",
  },
  {
    lat: -18.0,
    lng: 42.0,
    locationLabel: "Mozambique Channel",
    region: "Africa",
    occurredAt: "2025-01-09T23:48:00Z",
    shape: "orb",
    durationSec: 360,
    summary:
      "Research yacht spectrograph captured a green-white orb 2 km off the port beam. Emission lines did not match running lights or flares.",
    classification: "unidentified",
    confidence: 59,
    source: "field-report",
  },
  {
    lat: 21.3,
    lng: -157.85,
    locationLabel: "Oahu, Hawaii",
    region: "Pacific",
    occurredAt: "2026-03-04T04:12:00Z",
    shape: "triangle",
    durationSec: 80,
    summary:
      "Civil air patrol reported a silent black triangle crossing the leeward coast. Two ground cameras aligned on the same azimuth.",
    classification: "unidentified",
    confidence: 68,
    source: "field-report",
  },
  {
    lat: 40.42,
    lng: -3.7,
    locationLabel: "Madrid FIR",
    region: "Europe",
    occurredAt: "2025-04-28T21:55:00Z",
    shape: "lights",
    durationSec: 1500,
    summary:
      "A slow chevron of lights over the Sierra de Guadarrama. Photometric analysis favors a distant advertising rig, but no operator claimed the flight.",
    classification: "likely-prosaic",
    confidence: 41,
    source: "field-report",
  },
  {
    lat: 35.68,
    lng: 139.76,
    locationLabel: "Tokyo Bay",
    region: "East Asia",
    occurredAt: "2026-08-11T18:07:00Z",
    shape: "cylinder",
    durationSec: 55,
    summary:
      "Haneda departure reported a dark cylinder 400 ft off the left wing at 3,000 ft. TCAS empty. Camera phones from the shore show a brief silhouette.",
    classification: "sensor-contact",
    confidence: 72,
    source: "sensor",
  },
  {
    lat: 25.2,
    lng: 55.27,
    locationLabel: "Persian Gulf",
    region: "Middle East",
    occurredAt: "2024-02-14T16:40:00Z",
    shape: "orb",
    durationSec: 200,
    summary:
      "Tanker-crew video of a white orb that mirrored a helicopter's turns for three minutes, then climbed out of zoom. Regional UAV activity was high that week.",
    classification: "likely-prosaic",
    confidence: 46,
    source: "field-report",
  },
  {
    lat: 46.8,
    lng: -71.2,
    locationLabel: "St. Lawrence, Quebec",
    region: "North America",
    occurredAt: "2025-12-02T02:16:00Z",
    shape: "disc",
    durationSec: 400,
    summary:
      "Ice-road cameras recorded a disc-shaped return hovering over open water, then translating upriver without a wake.",
    classification: "unidentified",
    confidence: 62,
    source: "sensor",
  },
];
